Repository CMI-OSS/cbnu-alrami, pull requests merged in 2021-10, with the labels that each got.

#8 [FEAT] Make domitory restaurant scrapper
  scrapper-server/src/index.ts
  scrapper-server/src/interfaces/DomitoryFood.ts
  scrapper-server/src/interfaces/DomitoryScript.ts
  scrapper-server/src/scrappers/DomitoryScrapper/index.ts
  scrapper-server/src/scrappers/DomitoryScrapper/scripts/domitory.js
Labels: feature, 기숙사

#13 [Fix] Modify spelling errors (scraping, scraper)
  scrapper-server/src/index.ts
  scrapper-server/src/scrapers/CafeteriaScraper/index.ts
  scrapper-server/src/scrapers/CafeteriaScraper/scripts/cafeteria.js
  scrapper-server/src/scrapers/CalendarScraper/ArrayToDate.ts
  scrapper-server/src/scrapers/CalendarScraper/index.ts
  scrapper-server/src/scrapers/CalendarScraper/scripts/year.js
  scrapper-server/src/scrapers/DomitoryScraper/index.ts
  scrapper-server/src/scrapers/DomitoryScraper/scripts/domitory.js
  scrapper-server/src/scrapers/NoticeScraper/index.ts
  scrapper-server/src/scrapers/NoticeScraper/scripts/경영대학/경영정보학과.js
  scrapper-server/src/scrapers/NoticeScraper/scripts/경영대학/경영정보학과_대학원.js
  scrapper-server/src/scrapers/NoticeScraper/scripts/경영대학/경영학부.js
  scrapper-server/src/scrapers/NoticeScraper/scripts/경영대학/국제경영학과.js
  scrapper-server/src/scrapers/Scenario.ts
  scrapper-server/src/scrapers/Scraper.ts
Labels: fix

#15 [FEAT] Management Scraper State
  scrapper-server/src/common/Queue.ts
  scrapper-server/src/index.ts
  scrapper-server/src/scrapers/Scraper.ts
Labels: feature
