Repository CMI-OSS/cbnu-alrami, pull requests merged in 2023-08, with the labels that each got.

#968 [mobile] 구독 뒤로가기 분기처리
  packages/mobile/src/page/Setting/Menu/index.tsx
  packages/mobile/src/page/Setting/SettingTemplate/index.tsx
Labels: QA - 버그

#969 [mobile] 공지사항 컨텐츠 영역 이미지 사이즈 100% 자동 조절
  packages/mobile/src/page/Article/Detail/style.module.scss
Labels: 📱 Mobile, 💄 UI/UX

#970 [mobile] 미리보기 페이지에서 구독알림 설정할 수 있도록
  packages/mobile/src/components/atoms/icon/svg/index.ts
  packages/mobile/src/components/atoms/icon/svg/unSubscribe.svg
  packages/mobile/src/components/molecules/Drawer/index.tsx
  packages/mobile/src/components/shared/SubscriptionNoticeGroup/index.tsx
  packages/mobile/src/page/Board/Article/index.tsx
Labels: QA - 개선

#975 [mobile] 홈에서 식단 카드 클릭 시 식단 페이지로 이동
  packages/mobile/src/page/Home/Restaurant/EmptyCafeteria/index.tsx
  packages/mobile/src/page/Home/Restaurant/Selected/index.tsx
Labels: 👋 self-approve, QA - 개선

#976 [mobile] footer url 수정
  packages/mobile/src/components/molecules/Footer/index.tsx
Labels: 👋 self-approve, QA - 개선

#974 [mobile] 식당 디자인 변경
  packages/mobile/src/components/molecules/CafeteriaMenuCard/style.module.scss
  packages/mobile/src/components/molecules/MenuList/style.module.scss
Labels: ♻️ Refactor, 💄 UI/UX, QA - UI/UX

#980 [mobile] 아이콘 색상 수정
  packages/mobile/src/components/shared/SubscriptionNoticeGroup/index.tsx
Labels: ♻️ Refactor, 💄 UI/UX, QA - 버그
